### ISSUE TITLE
Looking for volunteers to read book chapter

### ISSUE THREAD

**Issue by kiegan** [CSAFE-ISU/slides#5]
Hi there, 

I would like two volunteers to read a chapter of the Forensic Stats book when it is completed in two weeks (or so). 

This particular chapter is called "The Path to the Witness Stand". It covers things like proficiency testing, black-box studies, etc. 

This will be 15-20 pages of general audience reading. This will most likely be the week of September 10th.

**Comment by srvanderplas** [comment]
I'm happy to help!
