### ISSUE TITLE
Updating / Building R libraries

### ISSUE THREAD

**Issue by bucephala** [CSAFE-ISU/slides#6]
**- problem context (what do we need to know before providing feedback?)**

Often I create small wrapper functions using Nick's existing handwriter package. Despite having the most up to date codebase in my local repo, using functions from the package (outside of the R command-line / interpreter) occasionally references the old, outdated code.

**- the specific problem/topic on which you'd like feedback (how can we help?)**

If anybody has run into a similar issue or is familiar with how R packages are built/imported.

**- a "so what?" (why is this important to your project?)**
Ensuring I can continue to write test wrapper functions to execute unit tests without running into older issues causing needless debugging festivals.

**Comment by sctyner** [comment]
Check out the R Packages book by Hadley Wickham: http://r-pkgs.had.co.nz/. I have read it cover-to-cover in physical book form (borrow from the library or @srvanderplas and  highly recommend.

This tells you everything you need to know about building and updating a package. Make sure you have the latest version of devtools installed: https://github.com/r-lib/devtools

Also @berryni you should check out Travis CI for checking package builds on Ubuntu: https://juliasilge.com/blog/beginners-guide-to-travis/ Also in the R packages book: http://r-pkgs.had.co.nz/check.html#travis

**Comment by bucephala** [comment]
Integration of the handwriter package into a web application involved many encounters with DevTools. I now feel comfortable resolving any future instances of this issue. 

Thank you Sam!
