### ISSUE TITLE
Putting figures side by side in CSAFE LaTeX poster

### ISSUE THREAD

**Issue by nategarton13** [CSAFE-ISU/slides#8]
I'm trying to create a poster for AAFS using the CSAFE poster template, and I am having a hard time figuring out how to put two figures side by side. Does anyone have any experience doing this? There doesn't seem to be much information online.

**Comment by markjlancaster** [comment]
Have you tried using the grid system in R?  It's fairly flexible for plot
layouts.
https://cran.r-project.org/web/packages/egg/vignettes/Ecosystem.html

**Comment by nategarton13** [comment]
Good idea. It looks like there are ways to add separate captions and subtitles. Thanks!
